replicaCount: 3

image:
  repository: "redis-sentinel"
  pullPolicy: IfNotPresent
  tag:  v.1.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
   limits:
     cpu: 500m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi

storage: 20Gi

ports:
   - name: loop-opt-port
     port: 8080
     protocol: TCP


nodeSelector: {}

tolerations: []

affinity: {}




#  helm upgrade -i loop-optimization -n=dev deployment/helm-chart
# redis-cli -h rfs-loop-opt-redis.dev -p 26379
